# Deployment yaml for deploying user micro-service in prd-ns(namespace)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-user-prd
  labels:
    app: i27-user-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i27-user-prd
  template:
    metadata:
      labels:
        app: i27-user-prd
    spec:
      containers:
      - name: i27-user-prd
        image: DIT #Image tag will be replaced by shared library
---
# Service yaml for user micro-service in prd-ns(namespace)
apiVersion: v1
kind: Service
metadata:
  name: i27-user-prd
  labels:
    app: i27-user-prd
spec:
  type: NodePort
  selector:
    app: i27-user-prd 
  ports:
  - port: 8232
    targetPort: 8232
      

                  